import { ExerciseConfig, CombatMove, RivalBoss } from '../types';

export const EXERCISES: Record<string, ExerciseConfig> = {
  squat: {
    id: 'ex_squat',
    name: 'Forge Squats',
    slug: 'squat',
    category: 'Lower Body Torque',
    targetMuscles: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'],
    unlockRequirementReps: 10,
    unlockedMoveId: 'iron_kick',
    description: 'Hydraulic knee bends generating rotational kick force.',
    properFormDescription: 'Lower hips until joint angle reaches <=110° (down phase), then drive upward to full extension >=160° (up phase).',
    demoTip: 'Drive hips backward and break 110° knee angle for a valid combat rep.',
    targetAngleDown: 110,
    targetAngleUp: 160,
    iconName: 'Activity',
    color: '#00F0FF',
  },
  pushup: {
    id: 'ex_pushup',
    name: 'Titan Push-ups',
    slug: 'pushup',
    category: 'Upper Body Burst',
    targetMuscles: ['Pectorals', 'Triceps', 'Front Deltoids', 'Core'],
    unlockRequirementReps: 10,
    unlockedMoveId: 'titan_punch',
    description: 'Horizontal kinetic presses generating hydraulic punch impact.',
    properFormDescription: 'Lower chest until elbows reach <=100° (down phase) with a straight spine, then push up to >=150° (up phase).',
    demoTip: 'Tuck elbows at 45° angle. Lower chest to floor without sagging hips.',
    targetAngleDown: 100,
    targetAngleUp: 150,
    iconName: 'Zap',
    color: '#FF0055',
  },
  lunge: {
    id: 'ex_lunge',
    name: 'Volt Lunges',
    slug: 'lunge',
    category: 'Unilateral Power',
    targetMuscles: ['Quadriceps', 'Glutes', 'Calves', 'Hip Stabilizers'],
    unlockRequirementReps: 10,
    unlockedMoveId: 'thunder_stride',
    description: 'Dynamic forward lunges conditioning servo balance and strike agility.',
    properFormDescription: 'Step forward and lower hips until front knee bends <=105°, then push back to standing >=155°.',
    demoTip: 'Keep torso upright. Drop hips into lunge stance.',
    targetAngleDown: 105,
    targetAngleUp: 155,
    iconName: 'Flame',
    color: '#FFE600',
  },
  jumping_jack: {
    id: 'ex_jumping_jack',
    name: 'Hyper Jumping Jacks',
    slug: 'jumping_jack',
    category: 'Full-Body Agility',
    targetMuscles: ['Calves', 'Deltoids', 'Lats', 'Core', 'Cardio Core'],
    unlockRequirementReps: 15,
    unlockedMoveId: 'nova_burst',
    description: 'Rapid kinetic arm-and-leg extensions overclocking heart-rate and burst agility.',
    properFormDescription: 'Raise arms overhead (>=135° arm elevation) with feet apart, then return to sides (<=65°).',
    demoTip: 'Elevate hands overhead and return to sides.',
    targetAngleDown: 65,
    targetAngleUp: 135,
    iconName: 'Sparkles',
    color: '#00FF66',
  },
  plank: {
    id: 'ex_plank',
    name: 'Aegis Plank Hold',
    slug: 'plank',
    category: 'Core Armor Integrity',
    targetMuscles: ['Transverse Abdominis', 'Rectus Abdominis', 'Glutes', 'Spinal Erectors'],
    unlockRequirementReps: 30, // 30 seconds
    unlockedMoveId: 'aegis_barrier',
    description: 'Isometric kinetic hold forging impenetrable defense shield armor.',
    properFormDescription: 'Maintain a straight line from shoulders through hips to ankles (alignment >=150°).',
    demoTip: 'Brace core tightly and pull belly button to spine.',
    targetAngleDown: 150,
    targetAngleUp: 175,
    isTimed: true,
    iconName: 'Shield',
    color: '#B026FF',
  },
};

export const INITIAL_MOVES: CombatMove[] = [
  {
    id: 'iron_kick',
    name: 'Iron Kick',
    exerciseSlug: 'squat',
    baseDamage: 25,
    requiredReps: 10,
    unlocked: true,
    masteryPercent: 100,
    description: 'A piston-driven roundhouse kick charged by deep squat repetitions.',
    iconName: 'Footprints',
    tier: 'Common',
    color: '#00F0FF',
  },
  {
    id: 'titan_punch',
    name: 'Titan Punch',
    exerciseSlug: 'pushup',
    baseDamage: 30,
    requiredReps: 10,
    unlocked: true,
    masteryPercent: 100,
    description: 'A heavy kinetic straight strike delivering compressed hydraulic force.',
    iconName: 'ShieldAlert',
    tier: 'Common',
    color: '#FF0055',
  },
  {
    id: 'thunder_stride',
    name: 'Thunder Stride',
    exerciseSlug: 'lunge',
    baseDamage: 32,
    requiredReps: 10,
    unlocked: true,
    masteryPercent: 100,
    description: 'An aggressive dashing thrust utilizing single-leg lunge torque.',
    iconName: 'Flame',
    tier: 'Common',
    color: '#FFE600',
  },
  {
    id: 'nova_burst',
    name: 'Nova Burst',
    exerciseSlug: 'jumping_jack',
    baseDamage: 35,
    requiredReps: 15,
    unlocked: true,
    masteryPercent: 100,
    description: 'A rapid radial energy pulse charged by high-cadence jumping jacks.',
    iconName: 'Zap',
    tier: 'Rare',
    color: '#00FF66',
  },
  {
    id: 'aegis_barrier',
    name: 'Aegis Barrier',
    exerciseSlug: 'plank',
    baseDamage: 40,
    requiredReps: 30,
    unlocked: true,
    masteryPercent: 100,
    description: 'A diamond-hard nanotech counter-barrier forged through plank endurance.',
    iconName: 'Shield',
    tier: 'Rare',
    color: '#B026FF',
  },
  {
    id: 'cyber_uppercut',
    name: 'Cyber Uppercut',
    exerciseSlug: 'squat',
    baseDamage: 45,
    requiredReps: 25,
    unlocked: true,
    masteryPercent: 100,
    description: 'An explosive upward surge lifting rivals into the air with leg power.',
    iconName: 'Flame',
    tier: 'Epic',
    color: '#00F0FF',
  },
  {
    id: 'forge_blast',
    name: 'Forge Blast',
    exerciseSlug: 'pushup',
    baseDamage: 52,
    requiredReps: 25,
    unlocked: true,
    masteryPercent: 100,
    description: 'A double-palm plasma shockwave unleashed from high push-up strength.',
    iconName: 'Zap',
    tier: 'Epic',
    color: '#FF0055',
  },
  {
    id: 'overclock_strike',
    name: 'Overclock Annihilator',
    exerciseSlug: 'all',
    baseDamage: 70,
    requiredReps: 50,
    unlocked: true,
    masteryPercent: 100,
    description: 'Ultimate cybernetic combo sequence overclocking all combat systems.',
    iconName: 'Swords',
    tier: 'Legendary',
    color: '#FFE600',
  },
];

export const RIVAL_BOSSES: RivalBoss[] = [
  {
    id: 'boss_aegis9',
    name: 'A.E.G.I.S-9',
    avatar: '🤖',
    title: 'Automated Defense Sentry',
    maxHp: 100,
    attackPower: 16,
    level: 1,
    description: 'Standard security unit running reactive nano-shielding algorithms.',
    unlockedAtLevel: 1,
    color: '#00F0FF',
  },
  {
    id: 'boss_vortex',
    name: 'VORTEX-X',
    avatar: '👾',
    title: 'Cyber Combat Synth',
    maxHp: 130,
    attackPower: 24,
    level: 2,
    description: 'Aggressive combat synth running offensive AI overdrive loops.',
    unlockedAtLevel: 2,
    color: '#B026FF',
  },
  {
    id: 'boss_nexus',
    name: 'NEXUS OVERLORD',
    avatar: '⚡',
    title: 'Apex Mechanical Colossus',
    maxHp: 175,
    attackPower: 32,
    level: 4,
    description: 'Heavy assault chassis armed with graviton pulses and tungsten plating.',
    unlockedAtLevel: 4,
    color: '#FF0055',
  },
];

export const LEVEL_TIERS = [
  { level: 1, title: 'CYBER NOVICE', minXp: 0, maxXp: 100 },
  { level: 2, title: 'CIRCUIT INITIATE', minXp: 100, maxXp: 300 },
  { level: 3, title: 'IRON GLADIATOR', minXp: 300, maxXp: 650 },
  { level: 4, title: 'TITAN STRIKER', minXp: 650, maxXp: 1100 },
  { level: 5, title: 'FORGE OVERLORD', minXp: 1100, maxXp: 2000 },
  { level: 6, title: 'APEX SENTINEL', minXp: 2000, maxXp: 5000 },
];